//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  clinicians: Clinicians;
  cliniciansConnection: CliniciansConnection;
  trustees: Trustees;
  trusteesConnection: TrusteesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCliniciansArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCliniciansConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CliniciansFilter>;
};


export type QueryTrusteesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTrusteesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TrusteesFilter>;
};

export type DocumentFilter = {
  clinicians?: InputMaybe<CliniciansFilter>;
  trustees?: InputMaybe<TrusteesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Clinicians | Trustees | Folder;

export type Clinicians = Node & Document & {
  __typename?: 'Clinicians';
  slug: Scalars['String']['output'];
  name: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  credentials?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  shortBio?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  specialties?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type CliniciansFilter = {
  slug?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  credentials?: InputMaybe<StringFilter>;
  shortBio?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  specialties?: InputMaybe<StringFilter>;
};

export type CliniciansConnectionEdges = {
  __typename?: 'CliniciansConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Clinicians>;
};

export type CliniciansConnection = Connection & {
  __typename?: 'CliniciansConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CliniciansConnectionEdges>>>;
};

export type Trustees = Node & Document & {
  __typename?: 'Trustees';
  slug: Scalars['String']['output'];
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  shortBio?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TrusteesFilter = {
  slug?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  shortBio?: InputMaybe<StringFilter>;
};

export type TrusteesConnectionEdges = {
  __typename?: 'TrusteesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Trustees>;
};

export type TrusteesConnection = Connection & {
  __typename?: 'TrusteesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TrusteesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateClinicians: Clinicians;
  createClinicians: Clinicians;
  updateTrustees: Trustees;
  createTrustees: Trustees;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateCliniciansArgs = {
  relativePath: Scalars['String']['input'];
  params: CliniciansMutation;
};


export type MutationCreateCliniciansArgs = {
  relativePath: Scalars['String']['input'];
  params: CliniciansMutation;
};


export type MutationUpdateTrusteesArgs = {
  relativePath: Scalars['String']['input'];
  params: TrusteesMutation;
};


export type MutationCreateTrusteesArgs = {
  relativePath: Scalars['String']['input'];
  params: TrusteesMutation;
};

export type DocumentUpdateMutation = {
  clinicians?: InputMaybe<CliniciansMutation>;
  trustees?: InputMaybe<TrusteesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  clinicians?: InputMaybe<CliniciansMutation>;
  trustees?: InputMaybe<TrusteesMutation>;
};

export type CliniciansMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  credentials?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  shortBio?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  specialties?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TrusteesMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  shortBio?: InputMaybe<Scalars['String']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type CliniciansFilter = {
  slug?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  credentials?: StringFilter | null | undefined;
  shortBio?: StringFilter | null | undefined;
  bio?: StringFilter | null | undefined;
  specialties?: StringFilter | null | undefined;
};

export type TrusteesFilter = {
  slug?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  shortBio?: StringFilter | null | undefined;
};

export type CliniciansPartsFragment = { __typename: 'Clinicians', slug: string, name: string, title: string | null, image: string | null, credentials: Array<string | null> | null, shortBio: string | null, bio: string | null, specialties: Array<string | null> | null };

export type TrusteesPartsFragment = { __typename: 'Trustees', slug: string, name: string, role: string | null, shortBio: string | null };

export type CliniciansQueryVariables = Exact<{
  relativePath: string;
}>;


export type CliniciansQuery = { clinicians: { __typename: 'Clinicians', id: string, slug: string, name: string, title: string | null, image: string | null, credentials: Array<string | null> | null, shortBio: string | null, bio: string | null, specialties: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type CliniciansConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: CliniciansFilter | null | undefined;
}>;


export type CliniciansConnectionQuery = { cliniciansConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Clinicians', id: string, slug: string, name: string, title: string | null, image: string | null, credentials: Array<string | null> | null, shortBio: string | null, bio: string | null, specialties: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TrusteesQueryVariables = Exact<{
  relativePath: string;
}>;


export type TrusteesQuery = { trustees: { __typename: 'Trustees', id: string, slug: string, name: string, role: string | null, shortBio: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TrusteesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: TrusteesFilter | null | undefined;
}>;


export type TrusteesConnectionQuery = { trusteesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Trustees', id: string, slug: string, name: string, role: string | null, shortBio: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const CliniciansPartsFragmentDoc = gql`
    fragment CliniciansParts on Clinicians {
  __typename
  slug
  name
  title
  image
  credentials
  shortBio
  bio
  specialties
}
    `;
export const TrusteesPartsFragmentDoc = gql`
    fragment TrusteesParts on Trustees {
  __typename
  slug
  name
  role
  shortBio
}
    `;
export const CliniciansDocument = gql`
    query clinicians($relativePath: String!) {
  clinicians(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CliniciansParts
  }
}
    ${CliniciansPartsFragmentDoc}`;
export const CliniciansConnectionDocument = gql`
    query cliniciansConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CliniciansFilter) {
  cliniciansConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CliniciansParts
      }
    }
  }
}
    ${CliniciansPartsFragmentDoc}`;
export const TrusteesDocument = gql`
    query trustees($relativePath: String!) {
  trustees(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TrusteesParts
  }
}
    ${TrusteesPartsFragmentDoc}`;
export const TrusteesConnectionDocument = gql`
    query trusteesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TrusteesFilter) {
  trusteesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TrusteesParts
      }
    }
  }
}
    ${TrusteesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      clinicians(variables: CliniciansQueryVariables, options?: C): Promise<{data: CliniciansQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CliniciansQueryVariables, query: string}> {
        return requester<{data: CliniciansQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CliniciansQueryVariables, query: string}, CliniciansQueryVariables>(CliniciansDocument, variables, options);
      },
    cliniciansConnection(variables?: CliniciansConnectionQueryVariables, options?: C): Promise<{data: CliniciansConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CliniciansConnectionQueryVariables, query: string}> {
        return requester<{data: CliniciansConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CliniciansConnectionQueryVariables, query: string}, CliniciansConnectionQueryVariables>(CliniciansConnectionDocument, variables, options);
      },
    trustees(variables: TrusteesQueryVariables, options?: C): Promise<{data: TrusteesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TrusteesQueryVariables, query: string}> {
        return requester<{data: TrusteesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TrusteesQueryVariables, query: string}, TrusteesQueryVariables>(TrusteesDocument, variables, options);
      },
    trusteesConnection(variables?: TrusteesConnectionQueryVariables, options?: C): Promise<{data: TrusteesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TrusteesConnectionQueryVariables, query: string}> {
        return requester<{data: TrusteesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TrusteesConnectionQueryVariables, query: string}, TrusteesConnectionQueryVariables>(TrusteesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  